### ISSUE TITLE
Doesnt work with Python 3.12

### ISSUE THREAD

**Issue by ErikGrankvist** [aisk/pick#110]
Updated to latest Python3.12 and my pick crashed, no output, just crashes

**Comment by lucasgerads** [comment]
Same issue.

**Operating System**
Windows 11 Version 22H2

**Python Version**
Python 3.12.1

**Comment by lucasgerads** [comment]
I think this is related to this issue: https://github.com/zephyrproject-rtos/windows-curses/issues/50

**Comment by wong2** [comment]
There's a workaround here: https://github.com/zephyrproject-rtos/windows-curses/issues/50#issuecomment-1840485627
PRs welcome!

**Comment by posen4u** [comment]
> There's a workaround here: [zephyrproject-rtos/windows-curses#50 (comment)](https://github.com/zephyrproject-rtos/windows-curses/issues/50#issuecomment-1840485627) PRs welcome!

I don't understand this workaround, how is it applied for pick?

**Comment by aisk** [comment]
This issue has already been resolved with the release of a new version v2.3.3 of windows-curses. Additionally, the GitHub issue https://github.com/zephyrproject-rtos/windows-curses/issues/50 has also been closed.
