### ISSUE TITLE
Pick no longer clears the page

### ISSUE THREAD

**Issue by gyang2300** [aisk/pick#123]
What happens: You ask the user to pick from list 1 and he picks something. You ask the user to pick from list 2 (The screen is not refreshed properly)

Expected Behavior: The second time you want the user to pick from a list, the screen should have refreshed.

Reproducible in pick v2.3.1
Not reproducible with previous pick versions.

Sample code on python 3.11.5 / pick 2.3.1 to demonstrate.
------------------------------------------------------------

#!/usr/bin/env python3

from pick import pick

title1 = 'Please choose your favorite programming language: '
title2 = 'Pick your fruit'
options1 = ['java', 'python', 'C++', 'Visual Basics', 'Perl']
options2 = ['apple','oranges','watermelon']
option1, index = pick(options1, title1)
option2, index = pick(options2, title2)

print(f"What does {option2} have to do with {option1}")

**Comment by aisk** [comment]
Thanks for reporting, see #124

**Comment by aisk** [comment]
Released with v2.3.2.
